WebApplication6/Models/EmailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication6.Models
{
    public class EmailModel
    {
        public int ID { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Urgancy { get; set; }
        public string IpAddress { get; set; }
        public string Location { get; set; }
        public DateTime date { get; set; }
    }
}

WebApplication6/Models/ResponseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebApplication6.Models
{
    public class ResponseContext : DbContext
    {    
        public ResponseContext() : base("name=ResponseContext")
        {
        }

        public System.Data.Entity.DbSet<WebApplication6.Models.EmailModel> EmailModels { get; set; }
    }
}

WebApplication6/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class ResponseController : Controller
    {
        private ResponseContext db = new ResponseContext();

        public ActionResult Index()
        {
            ViewBag.Message = Request.UserHostAddress;
            return View();
        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "ID,From,Subject,Body,Urgancy,IpAddress,Location,date")] EmailModel _objModelMail)
        {
            UniqueNumber();
            if (ModelState.IsValid)
            {
                _objModelMail.date = DateTime.Now;
                _objModelMail.IpAddress = GetIPAddress();
                //db.EmailModels.Add(_objModelMail);
                //db.SaveChanges();
                try
                {
                    string senderAd = "vincmelzp@gmail.com";
                    MailMessage mail = new MailMessage();
                    mail.To.Add(senderAd);
                    mail.From = new MailAddress(senderAd);
                    mail.Subject = _objModelMail.Urgancy;
                    string subject = _objModelMail.Subject;
                    string Type = _objModelMail.Urgancy;
                    string Body = _objModelMail.Body;
                    mail.Body = "Type: " + subject + Environment.NewLine + "Body: " + Body + Environment.NewLine + "IP Address" + GetIPAddress() + Environment.NewLine + "Online Number: " + UniqueNumber();
                    mail.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = new System.Net.NetworkCredential
                    ("vincmelzp@gmail.com", "P@umon66");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
                catch(Exception ex)
                {
                    Console.Write(ex.Message);
                }
                
                return RedirectToAction("Index");
            }
            else
            {
                return View("Index", _objModelMail);
            }
        }

        public static String GetIPAddress()
        {
            String ip =
                System.Web.HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            if (string.IsNullOrEmpty(ip))
                ip = System.Web.HttpContext.Current.Request.ServerVariables["REMOTE_ADDR"];
            else
                ip = ip.Split(',')[0];

            return ip;
        }
        public static String UniqueNumber()
        {
            string num = "0123456789";
            int len = num.Length;
            string otp = string.Empty;
            int otpdigit = 8;
            string finaldigit;
            int getindex;
            for(int i = 0; i < otpdigit; i++ )
            {
                do
                {
                    getindex = new Random().Next(0, len);
                    finaldigit = num.ToCharArray()[getindex].ToString();
                }
                while (otp.IndexOf(finaldigit) != -1);
                otp += finaldigit;
            }
            return otp;
        }

    }
}

WebApplication6/Views/Response/Index.cshtml
@model WebApplication6.Models.EmailModel

@{
    ViewBag.Title = "Index";
}

<body>
    <div class="Mail-form">
        <div class="row header">
            <h1>Polilert &nbsp;</h1>
            <h3>Fill out the form below to learn more!</h3>
        </div>

        <fieldset>

            @using (Html.BeginForm("Index", "Response", System.Web.Mvc.FormMethod.Post, new { id = "formEnter", @class = "form" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary()
                @*<div>
                        @Html.TextBoxFor(m => m.Geolocation, new { @id = "dataout", @class = "Geo-input" });
                    </div>*@
                <table>
                    <tr>
                        <td>@Html.RadioButtonFor(m => m.Urgancy, "Dont", new { id = "stateDont" }) @Html.Label("stateDont", "U")</td>
                        <div class="clear"></div>
                        <td>@Html.RadioButtonFor(m => m.Urgancy, "Maybe", new { id = "stateMaybe" }) @Html.Label("stateMaybe", "M")</td>
                        <div class="clear"></div>
                        <td>@Html.RadioButtonFor(m => m.Urgancy, "Reply", new { id = "stateReply" }) @Html.Label("stateReply", "R")</td>
                    </tr>
                </table>

                <div class="clear"></div>
                <ul>
                    <li id="left">
                        <p>From: </p>
                        <p>@Html.TextBoxFor(m => m.From)</p>
                    </li>
                    <li>
                        <p>Subject: </p>
                        <p>@Html.TextBoxFor(m => m.Subject)</p>
                    </li>
                    <li>
                        <p>Body: </p>
                        <p>@Html.TextAreaFor(m => m.Body)</p>
                    </li>
                    <li>
                        <p>Location: </p>
                        <p>@Html.EditorFor(m => m.Location)</p>
                    </li>

                </ul>
                <input class="submitform" type="submit" value="Send" onclick="geoFindMe()" />
                @*@Html.HiddenFor(m => m.Geolocation, new { id = "dataout" })*@
                <div type="hidden" id="dataout" name="dataout">
                    </div">

            }
    </fieldset>
</div>
</body>

WebApplication6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
        @RenderBody()
        
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/Geolocation.js"></script>
    
</body>
</html>